# Your GitHub Actions workflow
name: Sync Repositories

on:
  push:
    branches: [ main ]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Repo
        uses: actions/checkout@v2
        with:
          repository: 'mitre/caldera'
          token: ${{ secrets.YOUR_GITHUB_TOKEN }}
          path: 'caldera'

      - name: Sync Repositories
        run: |
          rsync -a --delete ./caldera/ .
          git config user.name 'davidfortytwo'
          git config user.email 'null'
          git add .
          git diff-index --quiet HEAD || git commit -m "Sync with source repo"
          git push
